name: snomedct
channels:
  - conda-forge
dependencies:
  - accelerate=0.26.1
  - aiofiles=23.2.1
  - aiohttp=3.9.1
  - dill=0.3.7
  - diskcache=5.6.3
  - einops=0.7.0
  - faiss-cpu=1.7.4
  - gensim=4.3.2
  - jsonpickle=3.0.2
  - keras=2.14.0
  - langchain=0.1.5
  - langchain-community=0.0.17
  - lightgbm=4.3.0
  - loguru=0.7.2
  - more-itertools=10.2.0
  - numba=0.59.0
  - numpy=1.26.4
  - pandas=2.2.0
  - peft=0.8.2
  - pip=24.0
  - polars=0.20.7
  - pytest=7.4.4
  - python=3.10.13
  - pytorch-lightning=2.1.3
  - pytorch::pytorch=2.1.2=*cpu*
  - scikit-learn=1.4.0
  - scipy=1.10.1
  - sentencepiece=0.1.99
  - sentence-transformers=2.5.1
  - spacy=3.6.1
  - statsmodels=0.14.1
  - tensorflow-base=2.14.0=cpu*
  - tensorflow=2.14.0=cpu*
  - tqdm=4.66.1
  - transformers=4.37.1
  - xarray=2024.1.1
  - pip:
    - scispacy==0.5.3
