name: snomedct
channels:
  - conda-forge
dependencies:
  - accelerate=0.25.0
  - aiofiles=23.2.1
  - aiohttp=3.8.5
  - diskcache=5.6.3
  - einops=0.7.0
  - gensim=4.3.2
  - jsonpickle=3.0.2
  - keras=2.13.1
  - lightgbm=4.1.0
  - loguru=0.7
  - numba=0.58
  - numpy=1.25.2
  - pandas=2.1.3
  - pip=23.3
  - pytest=7.4
  - python=3.10.13
  - pytorch-lightning=2.1.1
  - pytorch::pytorch=2.1.1=*cpu*
  - ray-default=2.8.1
  - scikit-learn=1.3.2
  - scipy=1.9.3
  - sentencepiece=0.1.99
  - spacy=3.7.2
  - statsmodels=0.14.0
  - tensorflow-base=2.13.1=cpu*
  - tensorflow=2.13.1=cpu*
  - tqdm=4.66
  - transformers=4.35.2
  - xarray=2023.11.0
